# Generated by Django 3.2.18 on 2023-08-05 18:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('commends', models.IntegerField()),
                ('replies', models.IntegerField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this post', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('topic', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('m', 'Maintenance'), ('t', 'Tankers'), ('s', 'Suez Max'), ('e', 'Engine Room')], max_length=200), blank=True, size=None)),
                ('date_posted', models.DateTimeField(auto_now=True, null=True)),
                ('contents', models.CharField(blank=True, max_length=10000, null=True)),
                ('commends', models.IntegerField(blank=True, default=0, null=True)),
                ('num_replies', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='posts.author')),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this post', primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(auto_now=True, null=True)),
                ('contents', models.CharField(blank=True, max_length=10000, null=True)),
                ('commends', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_author', to='posts.author')),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.post')),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
