# Generated by Django 3.2.18 on 2023-07-26 13:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('m', 'Maintenance'), ('t', 'Tankers'), ('s', 'Suez Max'), ('e', 'Engine Room')], max_length=200), blank=True, size=None),
        ),
    ]
