# Generated by Django 3.2.18 on 2023-07-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230726_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
