# Generated by Django 3.2.18 on 2023-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230810_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='replies',
        ),
        migrations.AddField(
            model_name='author',
            name='num_posts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='commends',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
