# Generated by Django 3.2.18 on 2023-08-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230810_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='commends',
        ),
        migrations.AlterField(
            model_name='reply',
            name='original_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_post', to='posts.post'),
        ),
    ]
