# Generated by Django 4.2 on 2023-05-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('hindi', 'Hindi'), ('english', 'English'), ('jp', 'Japanese'), ('CN', 'Mandarin')], default='enflish', help_text='Language', max_length=10),
        ),
    ]
