# Generated by Django 4.2 on 2023-05-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
